name: heychad
favicon: null
layout_spectrum: 0.11675161053426564
typography_spectrum: 0.30086184153333306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6024542613886297
  lightness: 0.6072386731393635
  saturation: 0.9631913953926414
  rhythmicContrast: 0.36734288511797786
purpose: []
